# Generated by Django 3.1.2 on 2020-10-08 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('gitlab', 'GitLab.com'), ('github', 'GitHub.com')], max_length=10, verbose_name='Тип репозитория')),
                ('url', models.CharField(max_length=50, verbose_name='Путь')),
                ('project_id', models.IntegerField(null=True, verbose_name='Project ID')),
            ],
            options={
                'verbose_name': 'репозитория',
                'verbose_name_plural': 'репозитории',
            },
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=50, verbose_name='Commit ID')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('message', models.CharField(max_length=100, verbose_name='Сообщение')),
                ('commit_time', models.DateTimeField(verbose_name='Дата создания')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commits.repository', verbose_name='Репозитории')),
            ],
            options={
                'verbose_name': 'коммит',
                'verbose_name_plural': 'коммиты',
                'ordering': ['-commit_time'],
            },
        ),
    ]
