# Generated by Django 3.1.2 on 2020-10-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='project_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Project ID'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.CharField(blank=True, help_text='В это поле необходим URL репозитория в следующем формате https://github.com/author_name/repository_name', max_length=50, verbose_name='Путь'),
        ),
    ]
