# Generated by Django 3.1.2 on 2020-10-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0002_auto_20201009_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='author_of_repo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='repository',
            name='repo_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
