# Generated by Django 3.1.2 on 2020-10-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0003_auto_20201009_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='author_of_repo',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='repo_name',
        ),
        migrations.AddField(
            model_name='repository',
            name='author_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Владелец репозитория'),
        ),
        migrations.AddField(
            model_name='repository',
            name='repository_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название репозитория'),
        ),
    ]
