# Generated by Django 3.1.2 on 2020-10-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0004_auto_20201009_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='author_name',
            field=models.CharField(blank=True, help_text='Автор репозитория необходим для GitHub', max_length=50, null=True, verbose_name='Владелец репозитория'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='project_id',
            field=models.IntegerField(blank=True, help_text='Номер репозитория необходим для GitLab', null=True, verbose_name='Project ID'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='repository_name',
            field=models.CharField(blank=True, help_text='В это поле необходим URL репозитория в следующем формате https://github.com/author_name/repository_name', max_length=50, null=True, verbose_name='Название репозитория'),
        ),
    ]
